CREATE DATABASE WE_PROJECT;
GO

USE WE_PROJECT;
GO

CREATE TABLE MEMBERS
(
    MEMBER_ID INT IDENTITY(1,1) PRIMARY KEY,  -- AUTO-INCREMENT
    M_ROLE VARCHAR(10),
    T_ID INT, -- Foreign Key
    USERNAME VARCHAR(50),
    DOB DATE,
    REGISTRATION_DATE DATE,
    EMAIL VARCHAR(100),
    PHONE VARCHAR(13),
    HEIGHT FLOAT,  -- Change DOUBLE to FLOAT in SQL Server
    WEIGHT FLOAT,  -- Change DOUBLE to FLOAT in SQL Server
    CORE_STRENGTH INT, 
    AVG_HEART_RATE INT
);
GO

CREATE TABLE SUBSCRIPTION
(
    SUB_ID INT IDENTITY(1,1) PRIMARY KEY,  -- AUTO-INCREMENT
    M_ID INT,  -- Foreign Key
    START_DATE DATE,
    END_DATE DATE,
    PRICE FLOAT,  -- Change DOUBLE to FLOAT in SQL Server
    STATUS VARCHAR(10),
    FOREIGN KEY (M_ID) REFERENCES MEMBERS(MEMBER_ID)
);
GO

CREATE TABLE ATTENDANCE
(
    A_ID INT IDENTITY(1,1) PRIMARY KEY,  -- AUTO-INCREMENT
    M_ID INT,  -- Foreign Key
    A_DATE DATE,
    FOREIGN KEY (M_ID) REFERENCES MEMBERS(MEMBER_ID)
);
GO

CREATE TABLE TRAINER
(
    T_ID INT IDENTITY(1,1) PRIMARY KEY,  -- AUTO-INCREMENT
    T_NAME VARCHAR(50),
    DOMAIN VARCHAR(100),
    EMAIL VARCHAR(100),
    PHONE VARCHAR(13),
    JOINING_DATE DATE,
    SALARY FLOAT  -- Change DOUBLE to FLOAT in SQL Server
);
GO

CREATE TABLE APPOINTMENTS
(
    A_ID INT IDENTITY(1,1) PRIMARY KEY,  -- AUTO-INCREMENT
    T_ID INT,  -- Foreign Key
    M_ID INT,  -- Foreign Key
    A_TIME TIME,
    A_DATE DATE,
    A_STATUS VARCHAR(20),
    FOREIGN KEY (T_ID) REFERENCES TRAINER(T_ID),
    FOREIGN KEY (M_ID) REFERENCES MEMBERS(MEMBER_ID)
);
GO

CREATE TABLE HEALTH
(
    H_ID INT IDENTITY(1,1) PRIMARY KEY,  -- AUTO-INCREMENT
    M_ID INT,  -- Foreign Key
    T_ID INT,  -- Foreign Key
    CALORIES INT,
    SLEEP_HOURS INT,
    H_DATE DATE,
    FOREIGN KEY (M_ID) REFERENCES MEMBERS(MEMBER_ID),
    FOREIGN KEY (T_ID) REFERENCES TRAINER(T_ID)
);
GO

CREATE TABLE PAYMENT
(
    P_ID INT IDENTITY(1,1) PRIMARY KEY,  -- AUTO-INCREMENT
    M_ID INT,  -- Foreign Key
    METHOD VARCHAR(20),
    AMOUNT FLOAT,  -- Change DOUBLE to FLOAT in SQL Server
    P_DATE DATE,
    FOREIGN KEY (M_ID) REFERENCES MEMBERS(MEMBER_ID)
);
GO

CREATE TABLE MESSAGE
(
    MESSAGE_HISTORY VARCHAR(200),
    M_ROLE VARCHAR(10),
    M_DATE DATE,
    M_TIME TIME  -- Fixed typo (M_ITME to M_TIME)
);
GO

CREATE TABLE EXERCISE
(
    E_ID INT IDENTITY(1,1) PRIMARY KEY,  -- AUTO-INCREMENT
    EXERCISE_NAME VARCHAR(100),
    E_DESCRIPTION VARCHAR(100),
    INTENSITY VARCHAR(100),
    MAXIMUM_SET INT
);
GO

CREATE TABLE SCHEDULE
(
    S_ID INT IDENTITY(1,1) PRIMARY KEY,  -- AUTO-INCREMENT
    M_ID INT,  -- Foreign Key
    T_ID INT,  -- Foreign Key
    EXERCISE_ID INT,  -- Foreign Key
    S_DATE DATE,
    NUMBER_SETS INT,
    FOREIGN KEY (M_ID) REFERENCES MEMBERS(MEMBER_ID),
    FOREIGN KEY (T_ID) REFERENCES TRAINER(T_ID),
    FOREIGN KEY (EXERCISE_ID) REFERENCES EXERCISE(E_ID)
);
GO

CREATE TABLE GOALS
(
    G_ID INT IDENTITY(1,1) PRIMARY KEY,  -- AUTO-INCREMENT
    M_ID INT,  -- Foreign Key
    GOAL_DESCRIPTION VARCHAR(100),
    MATRIX VARCHAR(100),
    FOREIGN KEY (M_ID) REFERENCES MEMBERS(MEMBER_ID)
);
GO

CREATE TABLE PROGRESS
(
    P_ID INT IDENTITY(1,1) PRIMARY KEY,  -- AUTO-INCREMENT
    G_ID INT,  -- Foreign Key
    M_ID INT,  -- Foreign Key
    DESCRIPT VARCHAR(100),
    P_STATUS VARCHAR(100),
    P_PERCENTAGE INT,
    FOREIGN KEY (G_ID) REFERENCES GOALS(G_ID),
    FOREIGN KEY (M_ID) REFERENCES MEMBERS(MEMBER_ID)
);
GO